# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            'GAP Days Fall 2017'
tagline:          'A GAP workshop'
description:      'Workshop: Aug 30 - Sep 1<br> Code sprint: Sep 4-8'
location:         'University of Siegen'
url:              http://gapdays.de
baseurl:          /gapdays2017-fall


exclude: [ "LICENSE.hyde.md", "README.hyde.md", "program.aux", "program.log", "program.out", "program.tex", "misc" ]
include: [ "SimplicialSurfaces.pdf" ]
