# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            'GAP Days Fall 2018'
tagline:          'A GAP workshop'
description:      'Sep 17 - Sep 21'
location:         'University of Siegen'
url:              http://gapdays.de
baseurl:          /gapdays2018-fall


exclude: [ "LICENSE.hyde.md", "README.hyde.md", "program.aux", "program.log", "program.out", "program.tex", "misc" ]
#include: [ "SimplicialSurfaces.pdf" ]
